- link:
    ~/Brewfile: Brewfile-ubuntu
- shell:
    - command: NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      stdout: true
      stderr: true

